[project]
name = "slop-scraper"
version = "0.1.0"
description = "Steam Launch Options (SLOP) Scraper CLI"
authors = [{ name = "Your Name" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "requests",
  "beautifulsoup4",
  "tqdm",
  "supabase"
]

[project.scripts]
slop-scraper = "slop_scraper.main:cli"
